apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/naveenao/kubernetes.git
    targetRevision: HEAD
    path: kubedeploy
  destination:
    server: https://kubernetes.default.svc
    namespace: sambappe

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
