apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserv-deploy
  labels:
    app: sambappe
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sambappe
  template:
    metadata:
      labels:
        app: sambappe
    spec:
      containers:
        - name: sambappe
          image: naveenao/customdockerimage:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: server-deploy
spec:
  type: NodePort
  selector:
    app: sambappe
  ports:
  - port:  8082
    targetPort: 8082
